### ISSUE TITLE
problem with angular 4.3x... Cannot find module 'ngx-ui-switch'

### ISSUE THREAD

**Issue by itcozum** [webcat12345/ngx-ui-switch#181]
hi,

I'm getting the below error after npm i

ERROR in D:/PROJELER/2017/tps-hr/web/src/app/system/personnel/personnel.module.ts (7,32): Cannot find module 'ngx-ui-switch'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ngx-ui-switch relative to D:/PROJELER/2017/tps-hr/web/s
ymbol PersonnelModule in D:/PROJELER/2017/tps-hr/web/src/app/system/personnel/personnel.module.ts, resolving symbol PersonnelModule in D:/PROJE
dule.ts
    at syntaxError (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler\bundles\compiler.umd.js:25118:23)
    at StaticReflector.simplify (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler\bundles\compiler.umd.js:25130:13)
    at StaticReflector.annotations (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler\bundles\compiler.umd.js:24558:41)
    at _getNgModuleMetadata (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\PROJELER\2017\tps-hr\web\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:3
    at AotPlugin._getLazyRoutesFromNgtools (D:\PROJELER\2017\tps-hr\web\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\PROJELER\2017\tps-hr\web\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by am-hs** [comment]
I got the same error. Working here with this:

`import { UiSwitchModule } from 'ngx-ui-switch/dist/es5';`

I think the "main" and/or "module" entries in package.json are missing.

**Comment by webcat12345** [comment]
@cmckni3 , please review last change. and could you please try to publish correct one to npm as version 1.4.2? I just tried this and 1.4.1 seems not working. I am trying to investigate what the problem is. This is urgent.

**Comment by webcat12345** [comment]
@cmckni3 , please test `npm publish` process.

**Comment by cmckni3** [comment]
I just published `1.4.4`. `npm publish` inside of `scripts` was running in the wrong directory when using yarn to run the script.

**Comment by webcat12345** [comment]
Cool let me test it.

**Comment by webcat12345** [comment]
Thanks @cmckni3 , it works as charm. I just checked AOT build as well.

**Comment by webcat12345** [comment]
@itcozum , @am-hs , let us know if issue has been solved.

**Comment by cmckni3** [comment]
No problem. I didn't test it before I had access to npm. Was lazy about changing the package name 😞

**Comment by am-hs** [comment]
@webcat12345 Thanks, it's working now 👍
